version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@prisma/client"
    versions:
    - 2.15.0
    - 2.16.0
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.21.0
    - 2.21.1
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
    - 7.4.1
  - dependency-name: winston-daily-rotate-file
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: nexus-prisma
    versions:
    - 0.16.2
    - 0.21.0
  - dependency-name: graphql-extensions
    versions:
    - 0.12.8
  - dependency-name: lodash
    versions:
    - 4.17.20
